import "dotenv/config";
import path from "node:path";
import { promises as fs } from "node:fs";
import mysql from "mysql2/promise";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const TAG = "[3Q-VAL-20260315]";
const PREFIX = "3Q-";

type IdMap = Record<string, number>;

function remark(text: string) {
  return `${TAG} ${text}`.trim();
}

function dateOnly(value: string) {
  return value;
}

function dateTime(value: string) {
  return value.replace("T", " ");
}

function buildSignature(
  id: number,
  signatureType: "inspector" | "reviewer" | "approver",
  signerName: string,
  signerDepartment: string,
  signedAt: string,
  signatureAction: string,
  signatureMeaning: string,
) {
  return {
    id,
    signatureType,
    signatureAction,
    signerName,
    signerDepartment,
    signedAt,
    signatureMeaning,
    status: "valid",
  };
}

async function insertRow(conn: mysql.Connection, table: string, data: Record<string, unknown>) {
  const keys = Object.keys(data);
  const placeholders = keys.map(() => "?").join(", ");
  const sql = `INSERT INTO \`${table}\` (${keys.map((key) => `\`${key}\``).join(", ")}) VALUES (${placeholders})`;
  const values = keys.map((key) => data[key]);
  const [result] = await conn.execute<mysql.ResultSetHeader>(sql, values);
  return Number(result.insertId);
}

async function queryRows<T = any>(conn: mysql.Connection, sql: string, params: unknown[] = []) {
  const [rows] = await conn.query(sql, params);
  return rows as T[];
}

async function queryOne<T = any>(conn: mysql.Connection, sql: string, params: unknown[] = []) {
  const rows = await queryRows<T>(conn, sql, params);
  return rows[0];
}

async function execute(conn: mysql.Connection, sql: string, params: unknown[] = []) {
  await conn.execute(sql, params);
}

async function ensureSterilizationProofPdf() {
  const virtualDir = "/ERP/生产部/生产入库申请/灭菌证明";
  const fileName = "3Q验证一次性无菌导尿包+3Q-ST-BATCH-001+3Q-FG-B20260315-01.pdf";
  const absoluteDir = path.resolve(process.cwd(), "uploads", virtualDir.replace(/^\/+/, ""));
  const absolutePath = path.join(absoluteDir, fileName);
  await fs.mkdir(absoluteDir, { recursive: true });

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([420, 297]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  page.drawText("3Q Validation Sterilization Proof", {
    x: 40,
    y: 230,
    size: 18,
    font,
    color: rgb(0.1, 0.1, 0.1),
  });
  page.drawText("Batch: 3Q-ST-BATCH-001", {
    x: 40,
    y: 190,
    size: 12,
    font,
  });
  page.drawText("Product batch: 3Q-FG-B20260315-01", {
    x: 40,
    y: 168,
    size: 12,
    font,
  });
  page.drawText("Result: EO sterilization completed for 100 sets.", {
    x: 40,
    y: 146,
    size: 12,
    font,
  });
  page.drawText("Generated by seed-3q-validation.ts", {
    x: 40,
    y: 124,
    size: 12,
    font,
  });
  const bytes = await pdf.save();
  await fs.writeFile(absolutePath, bytes);

  return {
    fileName,
    filePath: `${virtualDir}/${fileName}`,
    fileSize: bytes.length,
    uploadedAt: "2026-03-14T10:20:00",
  };
}

async function cleanup(conn: mysql.Connection) {
  const likePrefix = `${PREFIX}%`;
  const likeTag = `%${TAG}%`;

  await execute(conn, "DELETE FROM operation_logs WHERE description LIKE ? OR targetName LIKE ? OR newData LIKE ? OR previousData LIKE ?", [likeTag, likePrefix, likeTag, likeTag]);
  await execute(conn, "DELETE FROM recycle_bin WHERE displayName LIKE ? OR payload LIKE ?", [likePrefix, likeTag]);

  await execute(conn, "DELETE FROM order_approvals WHERE comment LIKE ? OR orderId IN (SELECT id FROM sales_orders WHERE orderNo LIKE ?) OR orderId IN (SELECT id FROM purchase_orders WHERE orderNo LIKE ?) OR orderId IN (SELECT id FROM production_orders WHERE orderNo LIKE ?)", [likeTag, likePrefix, likePrefix, likePrefix]);

  await execute(conn, "DELETE FROM payment_records WHERE recordNo LIKE ? OR relatedNo LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, likeTag]);
  await execute(conn, "DELETE FROM issued_invoices WHERE invoiceNo LIKE ? OR customerName LIKE ? OR remark LIKE ?", [likePrefix, "3Q验证%", likeTag]);
  await execute(conn, "DELETE FROM received_invoices WHERE invoiceNo LIKE ? OR supplierName LIKE ? OR remark LIKE ?", [likePrefix, "3Q验证%", likeTag]);
  await execute(conn, "DELETE FROM accounts_receivable WHERE invoiceNo LIKE ? OR invoiceNo LIKE ? OR remark LIKE ?", [likePrefix, "AR-3Q-%", likeTag]);
  await execute(conn, "DELETE FROM accounts_payable WHERE invoiceNo LIKE ? OR supplierName LIKE ? OR remark LIKE ?", [likePrefix, "3Q验证%", likeTag]);

  await execute(conn, "DELETE FROM inventory_transactions WHERE documentNo LIKE ? OR itemName LIKE ? OR batchNo LIKE ? OR remark LIKE ?", [likePrefix, "3Q验证%", likePrefix, likeTag]);
  await execute(conn, "DELETE FROM inventory WHERE materialCode LIKE ? OR itemName LIKE ? OR batchNo LIKE ? OR lotNo LIKE ?", [likePrefix, "3Q验证%", likePrefix, likePrefix]);

  await execute(conn, "DELETE FROM production_warehouse_entries WHERE entryNo LIKE ? OR productName LIKE ? OR batchNo LIKE ? OR remark LIKE ? OR quantityModifyReason LIKE ?", [likePrefix, "3Q验证%", likePrefix, likeTag, likeTag]);
  await execute(conn, "DELETE FROM sterilization_orders WHERE orderNo LIKE ? OR routingCardNo LIKE ? OR productName LIKE ? OR batchNo LIKE ? OR sterilizationBatchNo LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, "3Q验证%", likePrefix, likePrefix, likeTag]);
  await execute(conn, "DELETE FROM production_routing_cards WHERE cardNo LIKE ? OR productName LIKE ? OR batchNo LIKE ? OR remark LIKE ?", [likePrefix, "3Q验证%", likePrefix, likeTag]);
  await execute(conn, "DELETE FROM production_records WHERE recordNo LIKE ? OR productionOrderNo LIKE ? OR productName LIKE ? OR batchNo LIKE ? OR remark LIKE ? OR qualityNotes LIKE ?", [likePrefix, likePrefix, "3Q验证%", likePrefix, likeTag, likeTag]);
  await execute(conn, "DELETE FROM material_requisition_orders WHERE requisitionNo LIKE ? OR productionOrderNo LIKE ? OR remark LIKE ? OR items LIKE ?", [likePrefix, likePrefix, likeTag, likeTag]);
  await execute(conn, "DELETE FROM production_orders WHERE orderNo LIKE ? OR batchNo LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, likeTag]);
  await execute(conn, "DELETE FROM production_plans WHERE planNo LIKE ? OR salesOrderNo LIKE ? OR productName LIKE ? OR batchNo LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, "3Q验证%", likePrefix, likeTag]);

  await execute(conn, "DELETE FROM quality_inspections WHERE inspectionNo LIKE ? OR relatedDocNo LIKE ? OR itemName LIKE ? OR batchNo LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, "3Q验证%", likePrefix, likeTag]);

  await execute(conn, "DELETE FROM iqc_inspection_items WHERE iqcId IN (SELECT id FROM iqc_inspections WHERE inspectionNo LIKE ?)", [likePrefix]);
  await execute(conn, "DELETE FROM iqc_inspections WHERE inspectionNo LIKE ? OR goodsReceiptNo LIKE ? OR productName LIKE ? OR batchNo LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, "3Q验证%", likePrefix, likeTag]);

  await execute(conn, "DELETE FROM inspection_requirement_items WHERE requirementId IN (SELECT id FROM inspection_requirements WHERE requirementNo LIKE ?)", [likePrefix]);
  await execute(conn, "DELETE FROM inspection_requirements WHERE requirementNo LIKE ? OR productCode LIKE ? OR productName LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, "3Q验证%", likeTag]);

  await execute(conn, "DELETE FROM goods_receipt_items WHERE receiptId IN (SELECT id FROM goods_receipts WHERE receiptNo LIKE ?)", [likePrefix]);
  await execute(conn, "DELETE FROM goods_receipts WHERE receiptNo LIKE ? OR purchaseOrderNo LIKE ? OR supplierName LIKE ? OR inboundDocumentNo LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, "3Q验证%", likePrefix, likeTag]);

  await execute(conn, "DELETE FROM purchase_order_items WHERE orderId IN (SELECT id FROM purchase_orders WHERE orderNo LIKE ?)", [likePrefix]);
  await execute(conn, "DELETE FROM purchase_orders WHERE orderNo LIKE ? OR supplierName LIKE ? OR remark LIKE ?", [likePrefix, "3Q验证%", likeTag]);

  await execute(conn, "DELETE FROM material_request_items WHERE requestId IN (SELECT id FROM material_requests WHERE requestNo LIKE ?)", [likePrefix]);
  await execute(conn, "DELETE FROM material_requests WHERE requestNo LIKE ? OR reason LIKE ? OR remark LIKE ?", [likePrefix, likeTag, likeTag]);

  await execute(conn, "DELETE FROM sales_order_items WHERE orderId IN (SELECT id FROM sales_orders WHERE orderNo LIKE ?)", [likePrefix]);
  await execute(conn, "DELETE FROM sales_orders WHERE orderNo LIKE ? OR remark LIKE ? OR shippingAddress LIKE ?", [likePrefix, likeTag, "%3Q验证%"]);

  await execute(conn, "DELETE FROM sales_quote_items WHERE quoteId IN (SELECT id FROM sales_quotes WHERE quoteNo LIKE ?)", [likePrefix]);
  await execute(conn, "DELETE FROM sales_quotes WHERE quoteNo LIKE ? OR remark LIKE ? OR shippingAddress LIKE ?", [likePrefix, likeTag, "%3Q验证%"]);

  await execute(conn, "DELETE FROM product_supplier_prices WHERE productId IN (SELECT id FROM products WHERE code LIKE ?) OR supplierId IN (SELECT id FROM suppliers WHERE code LIKE ?)", [likePrefix, likePrefix]);
  await execute(conn, "DELETE FROM bom WHERE productId IN (SELECT id FROM products WHERE code LIKE ?) OR materialCode LIKE ? OR materialName LIKE ? OR remark LIKE ?", [likePrefix, likePrefix, "3Q验证%", likeTag]);

  await execute(conn, "DELETE FROM products WHERE code LIKE ? OR name LIKE ? OR description LIKE ?", [likePrefix, "3Q验证%", likeTag]);
  await execute(conn, "DELETE FROM suppliers WHERE code LIKE ? OR name LIKE ? OR address LIKE ?", [likePrefix, "3Q验证%", "%3Q验证%"]);
  await execute(conn, "DELETE FROM customers WHERE code LIKE ? OR name LIKE ? OR address LIKE ?", [likePrefix, "3Q验证%", "%3Q验证%"]);
}

async function main() {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL 未配置");
  }

  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  await conn.beginTransaction();

  try {
    const rawWarehouse = await queryOne<{ id: number; name: string }>(conn, "SELECT id, name FROM warehouses WHERE code = 'WH-RM-01' LIMIT 1");
    const finishedWarehouse = await queryOne<{ id: number; name: string }>(conn, "SELECT id, name FROM warehouses WHERE code = 'WH-FG-01' LIMIT 1");
    const auxWarehouse = await queryOne<{ id: number; name: string }>(conn, "SELECT id, name FROM warehouses WHERE code = 'WH-FL-01' LIMIT 1");
    const bankAccount = await queryOne<{ id: number; accountName: string; bankName: string; accountNo: string }>(
      conn,
      "SELECT id, accountName, bankName, accountNo FROM bank_accounts WHERE status = 'active' AND currency = 'CNY' ORDER BY isDefault DESC, id DESC LIMIT 1",
    );

    if (!rawWarehouse || !finishedWarehouse || !auxWarehouse || !bankAccount) {
      throw new Error("基础主数据缺失：仓库或银行账户未准备好");
    }

    const users = await queryRows<{ id: number; openId: string; name: string; department: string }>(
      conn,
      "SELECT id, openId, name, department FROM users WHERE openId IN ('user-admin','user-guojin','user-qiuchen','user-lxp','user-zhangjinfeng','user-wangting')",
    );
    const userByOpenId = new Map(users.map((user) => [user.openId, user]));
    const admin = userByOpenId.get("user-admin");
    const salesUser = userByOpenId.get("user-guojin");
    const purchaseUser = userByOpenId.get("user-qiuchen");
    const productionUser = userByOpenId.get("user-lxp");
    const qualityUser = userByOpenId.get("user-zhangjinfeng");
    const financeUser = userByOpenId.get("user-wangting");

    if (!admin || !salesUser || !purchaseUser || !productionUser || !qualityUser || !financeUser) {
      throw new Error("基础用户缺失，无法生成跨部门验证数据");
    }

    await cleanup(conn);
    const proofMeta = await ensureSterilizationProofPdf();

    const customer1Id = await insertRow(conn, "customers", {
      code: "3Q-CUST-001",
      name: "3Q验证-康泽医疗",
      shortName: "康泽医疗",
      type: "dealer",
      contactPerson: "刘珊",
      phone: "13800030001",
      email: "finance@3q-kangze.test",
      address: "江苏省苏州市工业园区3Q验证大道88号",
      province: "江苏省",
      city: "苏州市",
      paymentTerms: "账期支付",
      currency: "CNY",
      creditLimit: "300000.00",
      taxNo: "91320594MA3Q000001",
      taxRate: "13.00",
      bankName: "中国建设银行苏州分行",
      bankAccount: "320501000000000001",
      status: "active",
      source: "3Q验证样本",
      createdBy: salesUser.id,
      country: "中国",
      needInvoice: 1,
      salesPersonId: salesUser.id,
    });

    const customer2Id = await insertRow(conn, "customers", {
      code: "3Q-CUST-002",
      name: "3Q验证-天瑞耗材",
      shortName: "天瑞耗材",
      type: "domestic",
      contactPerson: "赵颖",
      phone: "13800030002",
      email: "order@3q-tianrui.test",
      address: "上海市浦东新区3Q验证支路18号",
      province: "上海市",
      city: "上海市",
      paymentTerms: "预付款",
      currency: "CNY",
      creditLimit: "50000.00",
      taxNo: "91310115MA3Q000002",
      taxRate: "13.00",
      bankName: "中国工商银行上海分行",
      bankAccount: "310501000000000002",
      status: "active",
      source: "3Q验证样本",
      createdBy: salesUser.id,
      country: "中国",
      needInvoice: 0,
      salesPersonId: salesUser.id,
    });

    const supplier1Id = await insertRow(conn, "suppliers", {
      code: "3Q-SUP-001",
      name: "3Q验证-医材原料供应商",
      shortName: "医材原料",
      type: "material",
      contactPerson: "钱峰",
      phone: "13900040001",
      email: "rm@3q-supplier.test",
      address: "苏州市吴中区原料路66号",
      businessLicense: "91320506MA3QSUP001",
      qualificationLevel: "A",
      paymentTerms: "账期支付",
      bankAccount: "622202000000000001",
      taxNo: "91320506MA3QSUP001",
      evaluationScore: "95.50",
      status: "qualified",
      createdBy: purchaseUser.id,
      creditDays: 30,
    });

    const supplier2Id = await insertRow(conn, "suppliers", {
      code: "3Q-SUP-002",
      name: "3Q验证-灭菌包装供应商",
      shortName: "灭菌包装",
      type: "material",
      contactPerson: "孙敏",
      phone: "13900040002",
      email: "pack@3q-supplier.test",
      address: "昆山市辅料路18号",
      businessLicense: "91320583MA3QSUP002",
      qualificationLevel: "A",
      paymentTerms: "预付款",
      bankAccount: "622202000000000002",
      taxNo: "91320583MA3QSUP002",
      evaluationScore: "92.00",
      status: "qualified",
      createdBy: purchaseUser.id,
      creditDays: 0,
    });

    const supplier3Id = await insertRow(conn, "suppliers", {
      code: "3Q-SUP-003",
      name: "3Q验证-委外灭菌服务商",
      shortName: "委外灭菌",
      type: "service",
      contactPerson: "陈诚",
      phone: "13900040003",
      email: "sterile@3q-supplier.test",
      address: "常熟市灭菌港9号",
      businessLicense: "91320581MA3QSUP003",
      qualificationLevel: "A",
      paymentTerms: "货到付款",
      bankAccount: "622202000000000003",
      taxNo: "91320581MA3QSUP003",
      evaluationScore: "97.00",
      status: "qualified",
      createdBy: purchaseUser.id,
      creditDays: 0,
    });

    const supplier4Id = await insertRow(conn, "suppliers", {
      code: "3Q-SUP-004",
      name: "3Q验证-物流服务商",
      shortName: "3Q物流",
      type: "service",
      contactPerson: "周扬",
      phone: "13900040004",
      email: "logistics@3q-supplier.test",
      address: "苏州市工业园区物流路3号",
      businessLicense: "91320594MA3QSUP004",
      qualificationLevel: "B",
      paymentTerms: "货到付款",
      bankAccount: "622202000000000004",
      taxNo: "91320594MA3QSUP004",
      evaluationScore: "89.80",
      status: "qualified",
      createdBy: purchaseUser.id,
      creditDays: 0,
    });

    const product1Id = await insertRow(conn, "products", {
      code: "3Q-PROD-001",
      name: "3Q验证一次性无菌导尿包",
      specification: "A型 16Fr",
      category: "医用耗材",
      unit: "套",
      auxiliaryUnit: "箱",
      conversionPrimaryQty: "1.0000",
      conversionAuxiliaryQty: "20.0000",
      registrationNo: "苏械注准20263000001",
      udiDi: "069123456789010001",
      manufacturer: "苏州神韵医疗器械有限公司",
      storageCondition: "阴凉干燥保存",
      shelfLife: 24,
      riskLevel: "II",
      status: "active",
      description: remark("医疗器械成品，验证用无菌产品"),
      createdBy: admin.id,
      sourceType: "production",
      needCustoms: 0,
      priceByPayment: JSON.stringify({
        "账期支付": 128,
        "预付款": 122,
      }),
      isMedicalDevice: 1,
      productCategory: "finished",
      productionClass: "成品",
      workshopAccess: "净化车间",
      salePermission: "saleable",
      procurePermission: "production_only",
      isSterilized: 1,
    });

    const product2Id = await insertRow(conn, "products", {
      code: "3Q-PROD-002",
      name: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      category: "原材料",
      unit: "kg",
      auxiliaryUnit: "卷",
      conversionPrimaryQty: "1.0000",
      conversionAuxiliaryQty: "5.0000",
      manufacturer: "3Q验证-医材原料供应商",
      storageCondition: "常温避光",
      shelfLife: 36,
      status: "active",
      description: remark("生产导尿包主原料"),
      createdBy: admin.id,
      sourceType: "purchase",
      needCustoms: 0,
      isMedicalDevice: 0,
      productCategory: "raw_material",
      productionClass: "原料",
      workshopAccess: "原料仓",
      salePermission: "not_saleable",
      procurePermission: "purchasable",
      isSterilized: 0,
    });

    const product3Id = await insertRow(conn, "products", {
      code: "3Q-PROD-003",
      name: "3Q验证纸塑灭菌袋",
      specification: "200mm*300mm",
      category: "包装辅料",
      unit: "个",
      auxiliaryUnit: "包",
      conversionPrimaryQty: "1.0000",
      conversionAuxiliaryQty: "50.0000",
      manufacturer: "3Q验证-灭菌包装供应商",
      storageCondition: "常温干燥",
      shelfLife: 24,
      status: "active",
      description: remark("导尿包包装辅料"),
      createdBy: admin.id,
      sourceType: "purchase",
      needCustoms: 0,
      isMedicalDevice: 0,
      productCategory: "packaging_material",
      productionClass: "辅料",
      workshopAccess: "辅料仓",
      salePermission: "not_saleable",
      procurePermission: "purchasable",
      isSterilized: 0,
    });

    const product4Id = await insertRow(conn, "products", {
      code: "3Q-PROD-004",
      name: "3Q验证引流固定贴",
      specification: "普通型 10片/盒",
      category: "成品耗材",
      unit: "盒",
      auxiliaryUnit: "箱",
      conversionPrimaryQty: "1.0000",
      conversionAuxiliaryQty: "24.0000",
      manufacturer: "苏州神韵医疗器械有限公司",
      storageCondition: "常温",
      shelfLife: 18,
      status: "active",
      description: remark("非医疗器械，直接销售样例"),
      createdBy: admin.id,
      sourceType: "purchase",
      needCustoms: 0,
      priceByPayment: JSON.stringify({
        "预付款": 96,
        "货到付款": 102,
      }),
      isMedicalDevice: 0,
      productCategory: "finished",
      productionClass: "外购成品",
      workshopAccess: "成品仓",
      salePermission: "saleable",
      procurePermission: "purchasable",
      isSterilized: 0,
    });

    await insertRow(conn, "product_supplier_prices", {
      productId: product2Id,
      supplierId: supplier1Id,
      unitPrice: "180.0000",
      currency: "CNY",
      minOrderQty: 10,
      leadTimeDays: 5,
      isDefault: 1,
      effectiveDate: dateOnly("2026-03-01"),
      remark: remark("主原料默认采购价"),
      createdBy: purchaseUser.id,
    });

    await insertRow(conn, "product_supplier_prices", {
      productId: product3Id,
      supplierId: supplier2Id,
      unitPrice: "1.8000",
      currency: "CNY",
      minOrderQty: 100,
      leadTimeDays: 3,
      isDefault: 1,
      effectiveDate: dateOnly("2026-03-01"),
      remark: remark("包装辅料默认采购价"),
      createdBy: purchaseUser.id,
    });

    await insertRow(conn, "product_supplier_prices", {
      productId: product4Id,
      supplierId: supplier2Id,
      unitPrice: "52.0000",
      currency: "CNY",
      minOrderQty: 20,
      leadTimeDays: 4,
      isDefault: 1,
      effectiveDate: dateOnly("2026-03-01"),
      remark: remark("外购成品采购价"),
      createdBy: purchaseUser.id,
    });

    await insertRow(conn, "bom", {
      productId: product1Id,
      baseProductQty: "1.0000",
      baseProductUnit: "套",
      materialCode: "3Q-PROD-002",
      materialName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      quantity: "0.2000",
      unit: "kg",
      version: "V1.0",
      status: "active",
      parentId: null,
      level: 2,
      unitPrice: "180.0000",
      remark: remark("每套用量 0.2kg"),
      bomCode: "3Q-BOM-001",
      effectiveDate: dateOnly("2026-03-01"),
    });

    await insertRow(conn, "bom", {
      productId: product1Id,
      baseProductQty: "1.0000",
      baseProductUnit: "套",
      materialCode: "3Q-PROD-003",
      materialName: "3Q验证纸塑灭菌袋",
      specification: "200mm*300mm",
      quantity: "1.0000",
      unit: "个",
      version: "V1.0",
      status: "active",
      parentId: null,
      level: 2,
      unitPrice: "1.8000",
      remark: remark("每套用量 1 个"),
      bomCode: "3Q-BOM-001",
      effectiveDate: dateOnly("2026-03-01"),
    });

    const iqcRequirementId = await insertRow(conn, "inspection_requirements", {
      requirementNo: "3Q-IQC-REQ-001",
      type: "IQC",
      productCode: "3Q-PROD-002",
      productName: "3Q验证医用硅胶原料",
      version: "V1.0",
      status: "active",
      remark: remark("原料 IQC 检验要求"),
      createdBy: qualityUser.id,
    });

    await insertRow(conn, "inspection_requirement_items", {
      requirementId: iqcRequirementId,
      sourceDataId: "3Q-IQC-1",
      itemName: "外观",
      itemType: "qualitative",
      standard: "颜色均匀、无异物、无破损",
      acceptedValues: "合格,不合格",
      sortOrder: 1,
      remark: remark("外观检验"),
      standardRequirement: "颜色均匀、无异物、无破损",
      standardBasis: "原料来料标准",
      inspectionRequirement: "目视检查",
    });

    await insertRow(conn, "inspection_requirement_items", {
      requirementId: iqcRequirementId,
      sourceDataId: "3Q-IQC-2",
      itemName: "尺寸",
      itemType: "quantitative",
      standard: "外径 4.0±0.1 mm",
      minVal: "3.9000",
      maxVal: "4.1000",
      unit: "mm",
      sortOrder: 2,
      remark: remark("尺寸检验"),
      standardRequirement: "外径 4.0±0.1 mm",
      standardBasis: "产品图纸 3Q-SJ-001",
      inspectionRequirement: "游标卡尺测量",
    });

    const ipqcRequirementId = await insertRow(conn, "inspection_requirements", {
      requirementNo: "3Q-IPQC-REQ-001",
      type: "IPQC",
      productCode: "3Q-PROD-001",
      productName: "3Q验证一次性无菌导尿包",
      version: "V1.0",
      status: "active",
      remark: remark("过程检验要求"),
      createdBy: qualityUser.id,
    });

    await insertRow(conn, "inspection_requirement_items", {
      requirementId: ipqcRequirementId,
      sourceDataId: "3Q-IPQC-1",
      itemName: "装配完整性",
      itemType: "qualitative",
      standard: "组件装配完整，无错漏装",
      acceptedValues: "合格,不合格",
      sortOrder: 1,
      remark: remark("装配检验"),
      standardRequirement: "组件装配完整，无错漏装",
      standardBasis: "作业指导书 WI-3Q-01",
      inspectionRequirement: "目视 + 对照首件",
    });

    await insertRow(conn, "inspection_requirement_items", {
      requirementId: ipqcRequirementId,
      sourceDataId: "3Q-IPQC-2",
      itemName: "流量测试",
      itemType: "quantitative",
      standard: "20-24 ml/min",
      minVal: "20.0000",
      maxVal: "24.0000",
      unit: "ml/min",
      sortOrder: 2,
      remark: remark("功能检验"),
      standardRequirement: "20-24 ml/min",
      standardBasis: "过程控制规范 3Q-PC-01",
      inspectionRequirement: "功能工装检测",
    });

    const oqcRequirementId = await insertRow(conn, "inspection_requirements", {
      requirementNo: "3Q-OQC-REQ-001",
      type: "OQC",
      productCode: "3Q-PROD-001",
      productName: "3Q验证一次性无菌导尿包",
      version: "V1.0",
      status: "active",
      remark: remark("成品放行检验要求"),
      createdBy: qualityUser.id,
    });

    await insertRow(conn, "inspection_requirement_items", {
      requirementId: oqcRequirementId,
      sourceDataId: "3Q-OQC-1",
      itemName: "无菌屏障完整性",
      itemType: "qualitative",
      standard: "包装完整，封边无破损",
      acceptedValues: "合格,不合格",
      sortOrder: 1,
      remark: JSON.stringify({
        note: remark("放行项目 1"),
        reviewStandard: "包装完整，封边无破损",
      }),
      standardRequirement: "包装完整，封边无破损",
      standardBasis: "包装验证报告 PV-3Q-01",
      inspectionRequirement: "目视检查",
    });

    await insertRow(conn, "inspection_requirement_items", {
      requirementId: oqcRequirementId,
      sourceDataId: "3Q-OQC-2",
      itemName: "标签信息",
      itemType: "qualitative",
      standard: "批号、UDI、有效期打印正确",
      acceptedValues: "合格,不合格",
      sortOrder: 2,
      remark: JSON.stringify({
        note: remark("放行项目 2"),
        reviewStandard: "批号、UDI、有效期打印正确",
      }),
      standardRequirement: "批号、UDI、有效期打印正确",
      standardBasis: "标签管理规程 LP-3Q-01",
      inspectionRequirement: "逐项核对",
    });

    const materialRequest1Id = await insertRow(conn, "material_requests", {
      requestNo: "3Q-PR-001",
      department: "生产部",
      requesterId: productionUser.id,
      requestDate: dateOnly("2026-03-03"),
      urgency: "urgent",
      reason: remark("销售订单 3Q-SO-001 驱动的生产备料"),
      totalAmount: "9216.00",
      status: "completed",
      approvedBy: admin.id,
      approvedAt: dateTime("2026-03-03T11:20:00"),
      remark: remark("已拆分为原料与辅料两张采购单"),
    });

    await insertRow(conn, "material_request_items", {
      requestId: materialRequest1Id,
      productId: product2Id,
      materialName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      quantity: "50.0000",
      unit: "kg",
      estimatedPrice: "180.0000",
      remark: remark("主原料采购"),
    });

    await insertRow(conn, "material_request_items", {
      requestId: materialRequest1Id,
      productId: product3Id,
      materialName: "3Q验证纸塑灭菌袋",
      specification: "200mm*300mm",
      quantity: "120.0000",
      unit: "个",
      estimatedPrice: "1.8000",
      remark: remark("包装辅料采购"),
    });

    const materialRequest2Id = await insertRow(conn, "material_requests", {
      requestNo: "3Q-PR-002",
      department: "销售部",
      requesterId: salesUser.id,
      requestDate: dateOnly("2026-03-05"),
      urgency: "normal",
      reason: remark("预付款订单外购成品备货"),
      totalAmount: "1560.00",
      status: "cancelled",
      approvedBy: admin.id,
      approvedAt: dateTime("2026-03-05T10:10:00"),
      remark: remark("客户未支付预付款，备货申请关闭"),
    });

    await insertRow(conn, "material_request_items", {
      requestId: materialRequest2Id,
      productId: product4Id,
      materialName: "3Q验证引流固定贴",
      specification: "普通型 10片/盒",
      quantity: "30.0000",
      unit: "盒",
      estimatedPrice: "52.0000",
      remark: remark("外购成品备货"),
    });

    const purchaseOrder1Id = await insertRow(conn, "purchase_orders", {
      orderNo: "3Q-PO-001",
      supplierId: supplier1Id,
      supplierName: "3Q验证-医材原料供应商",
      orderDate: dateOnly("2026-03-04"),
      expectedDate: dateOnly("2026-03-08"),
      totalAmount: "9000.00",
      currency: "CNY",
      status: "completed",
      deptApprovalStatus: "approved",
      gmApprovalStatus: "approved",
      printedAt: dateTime("2026-03-04T15:30:00"),
      paymentStatus: "paid",
      remark: remark("原料采购单，已收货并已付款"),
      buyerId: purchaseUser.id,
      approvedBy: admin.id,
      approvedAt: dateTime("2026-03-04T14:20:00"),
      createdBy: purchaseUser.id,
      amountBase: "9000.00",
      exchangeRate: "1.000000",
      materialRequestId: materialRequest1Id,
      totalAmountBase: "9000.00",
    });

    const po1ItemId = await insertRow(conn, "purchase_order_items", {
      orderId: purchaseOrder1Id,
      productId: product2Id,
      materialCode: "3Q-PROD-002",
      materialName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      quantity: "50.0000",
      unit: "kg",
      unitPrice: "180.0000",
      amount: "9000.00",
      receivedQty: "50.0000",
      remark: remark("全检通过后入库"),
    });

    const purchaseOrder2Id = await insertRow(conn, "purchase_orders", {
      orderNo: "3Q-PO-002",
      supplierId: supplier2Id,
      supplierName: "3Q验证-灭菌包装供应商",
      orderDate: dateOnly("2026-03-04"),
      expectedDate: dateOnly("2026-03-09"),
      totalAmount: "216.00",
      currency: "CNY",
      status: "completed",
      deptApprovalStatus: "approved",
      gmApprovalStatus: "approved",
      printedAt: dateTime("2026-03-04T16:10:00"),
      paymentStatus: "paid",
      remark: remark("包装辅料采购单，已收货并已付款"),
      buyerId: purchaseUser.id,
      approvedBy: admin.id,
      approvedAt: dateTime("2026-03-04T15:40:00"),
      createdBy: purchaseUser.id,
      amountBase: "216.00",
      exchangeRate: "1.000000",
      materialRequestId: materialRequest1Id,
      totalAmountBase: "216.00",
    });

    const po2ItemId = await insertRow(conn, "purchase_order_items", {
      orderId: purchaseOrder2Id,
      productId: product3Id,
      materialCode: "3Q-PROD-003",
      materialName: "3Q验证纸塑灭菌袋",
      specification: "200mm*300mm",
      quantity: "120.0000",
      unit: "个",
      unitPrice: "1.8000",
      amount: "216.00",
      receivedQty: "120.0000",
      remark: remark("包装辅料"),
    });

    const purchaseOrder3Id = await insertRow(conn, "purchase_orders", {
      orderNo: "3Q-PO-003",
      supplierId: supplier1Id,
      supplierName: "3Q验证-医材原料供应商",
      orderDate: dateOnly("2026-03-05"),
      expectedDate: dateOnly("2026-03-10"),
      totalAmount: "3500.00",
      currency: "CNY",
      status: "cancelled",
      deptApprovalStatus: "approved",
      gmApprovalStatus: "approved",
      printedAt: dateTime("2026-03-05T11:30:00"),
      paymentStatus: "unpaid",
      remark: remark("异常场景：来料检验不合格后采购关闭"),
      buyerId: purchaseUser.id,
      approvedBy: admin.id,
      approvedAt: dateTime("2026-03-05T10:50:00"),
      createdBy: purchaseUser.id,
      amountBase: "3500.00",
      exchangeRate: "1.000000",
      materialRequestId: materialRequest1Id,
      totalAmountBase: "3500.00",
    });

    const po3ItemId = await insertRow(conn, "purchase_order_items", {
      orderId: purchaseOrder3Id,
      productId: product2Id,
      materialCode: "3Q-PROD-002",
      materialName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      quantity: "20.0000",
      unit: "kg",
      unitPrice: "175.0000",
      amount: "3500.00",
      receivedQty: "20.0000",
      remark: remark("异常批次"),
    });

    const goodsReceipt1Id = await insertRow(conn, "goods_receipts", {
      receiptNo: "3Q-GR-001",
      purchaseOrderId: purchaseOrder1Id,
      purchaseOrderNo: "3Q-PO-001",
      supplierId: supplier1Id,
      supplierName: "3Q验证-医材原料供应商",
      warehouseId: rawWarehouse.id,
      receiptDate: dateOnly("2026-03-09"),
      status: "warehoused",
      inspectorId: qualityUser.id,
      inspectorName: qualityUser.name,
      inspectionDate: dateOnly("2026-03-09"),
      inspectionResult: "pass",
      inspectionRemark: remark("IQC 合格，允许入库"),
      inboundDocumentNo: "3Q-IN-001",
      inboundAt: dateTime("2026-03-09T15:20:00"),
      remark: remark("原料到货已完成检验和入库"),
      createdBy: purchaseUser.id,
    });

    const goodsReceipt1ItemId = await insertRow(conn, "goods_receipt_items", {
      receiptId: goodsReceipt1Id,
      purchaseOrderItemId: po1ItemId,
      productId: product2Id,
      materialCode: "3Q-PROD-002",
      materialName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      unit: "kg",
      orderedQty: "50.0000",
      receivedQty: "50.0000",
      batchNo: "3Q-RM-B20260309-01",
      sterilizationBatchNo: null,
      inspectionQty: "50.0000",
      qualifiedQty: "50.0000",
      unqualifiedQty: "0.0000",
      remark: remark("合格批次"),
    });

    const goodsReceipt2Id = await insertRow(conn, "goods_receipts", {
      receiptNo: "3Q-GR-002",
      purchaseOrderId: purchaseOrder2Id,
      purchaseOrderNo: "3Q-PO-002",
      supplierId: supplier2Id,
      supplierName: "3Q验证-灭菌包装供应商",
      warehouseId: auxWarehouse.id,
      receiptDate: dateOnly("2026-03-10"),
      status: "warehoused",
      inspectorId: qualityUser.id,
      inspectorName: qualityUser.name,
      inspectionDate: dateOnly("2026-03-10"),
      inspectionResult: "pass",
      inspectionRemark: remark("辅料外观合格"),
      inboundDocumentNo: "3Q-IN-002",
      inboundAt: dateTime("2026-03-10T11:30:00"),
      remark: remark("包装辅料已入库"),
      createdBy: purchaseUser.id,
    });

    const goodsReceipt2ItemId = await insertRow(conn, "goods_receipt_items", {
      receiptId: goodsReceipt2Id,
      purchaseOrderItemId: po2ItemId,
      productId: product3Id,
      materialCode: "3Q-PROD-003",
      materialName: "3Q验证纸塑灭菌袋",
      specification: "200mm*300mm",
      unit: "个",
      orderedQty: "120.0000",
      receivedQty: "120.0000",
      batchNo: "3Q-PM-B20260310-01",
      sterilizationBatchNo: null,
      inspectionQty: "120.0000",
      qualifiedQty: "120.0000",
      unqualifiedQty: "0.0000",
      remark: remark("辅料合格"),
    });

    const goodsReceipt3Id = await insertRow(conn, "goods_receipts", {
      receiptNo: "3Q-GR-003",
      purchaseOrderId: purchaseOrder3Id,
      purchaseOrderNo: "3Q-PO-003",
      supplierId: supplier1Id,
      supplierName: "3Q验证-医材原料供应商",
      warehouseId: rawWarehouse.id,
      receiptDate: dateOnly("2026-03-11"),
      status: "failed",
      inspectorId: qualityUser.id,
      inspectorName: qualityUser.name,
      inspectionDate: dateOnly("2026-03-11"),
      inspectionResult: "fail",
      inspectionRemark: remark("原料尺寸超差，不允许入库"),
      remark: remark("异常到货单"),
      createdBy: purchaseUser.id,
    });

    const goodsReceipt3ItemId = await insertRow(conn, "goods_receipt_items", {
      receiptId: goodsReceipt3Id,
      purchaseOrderItemId: po3ItemId,
      productId: product2Id,
      materialCode: "3Q-PROD-002",
      materialName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      unit: "kg",
      orderedQty: "20.0000",
      receivedQty: "20.0000",
      batchNo: "3Q-RM-B20260311-99",
      sterilizationBatchNo: null,
      inspectionQty: "20.0000",
      qualifiedQty: "0.0000",
      unqualifiedQty: "20.0000",
      remark: remark("不合格批次"),
    });

    const iqc1Id = await insertRow(conn, "iqc_inspections", {
      inspectionNo: "3Q-IQC-001",
      reportMode: "online",
      goodsReceiptId: goodsReceipt1Id,
      goodsReceiptNo: "3Q-GR-001",
      goodsReceiptItemId: goodsReceipt1ItemId,
      productId: product2Id,
      productCode: "3Q-PROD-002",
      productName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      supplierId: supplier1Id,
      supplierName: "3Q验证-医材原料供应商",
      supplierCode: "3Q-SUP-001",
      batchNo: "3Q-RM-B20260309-01",
      sterilizationBatchNo: null,
      receivedQty: "50.0000",
      sampleQty: "5.0000",
      qualifiedQty: "50.0000",
      unit: "kg",
      inspectionRequirementId: iqcRequirementId,
      inspectionDate: dateOnly("2026-03-09"),
      inspectorId: qualityUser.id,
      inspectorName: qualityUser.name,
      result: "passed",
      remark: remark("IQC 合格，允许全量入库"),
      attachments: JSON.stringify([{ fileName: "3Q-IQC-001-photo.jpg", filePath: "/ERP/质量部/IQC/3Q-IQC-001-photo.jpg", mimeType: "image/jpeg" }]),
      signatures: JSON.stringify([
        buildSignature(301, "inspector", qualityUser.name, "质量部", "2026-03-09T10:12:00", "检验", "本人确认已按照检验规程对来料进行检验，检验结果真实、准确、完整。"),
        buildSignature(302, "reviewer", admin.name, "管理部", "2026-03-09T10:18:00", "复核", "本人确认已复核检验记录，数据真实可靠，检验方法符合规定。"),
      ]),
      createdBy: qualityUser.id,
    });

    await insertRow(conn, "iqc_inspection_items", {
      iqcId: iqc1Id,
      requirementItemId: 1,
      itemName: "外观",
      itemType: "qualitative",
      standard: "颜色均匀、无异物、无破损",
      acceptedValues: "合格,不合格",
      actualValue: "合格",
      conclusion: "pass",
      sortOrder: 1,
      remark: remark("外观符合要求"),
    });

    await insertRow(conn, "iqc_inspection_items", {
      iqcId: iqc1Id,
      requirementItemId: 2,
      itemName: "尺寸",
      itemType: "quantitative",
      standard: "外径 4.0±0.1 mm",
      minVal: "3.9000",
      maxVal: "4.1000",
      unit: "mm",
      measuredValue: "4.02",
      sampleValues: JSON.stringify(["4.01", "4.02", "4.03"]),
      actualValue: "4.02",
      conclusion: "pass",
      sortOrder: 2,
      remark: remark("尺寸在控制范围内"),
    });

    const iqc2Id = await insertRow(conn, "iqc_inspections", {
      inspectionNo: "3Q-IQC-002",
      reportMode: "offline",
      goodsReceiptId: goodsReceipt2Id,
      goodsReceiptNo: "3Q-GR-002",
      goodsReceiptItemId: goodsReceipt2ItemId,
      productId: product3Id,
      productCode: "3Q-PROD-003",
      productName: "3Q验证纸塑灭菌袋",
      specification: "200mm*300mm",
      supplierId: supplier2Id,
      supplierName: "3Q验证-灭菌包装供应商",
      supplierCode: "3Q-SUP-002",
      batchNo: "3Q-PM-B20260310-01",
      sterilizationBatchNo: null,
      receivedQty: "120.0000",
      sampleQty: "12.0000",
      qualifiedQty: "120.0000",
      unit: "个",
      inspectionRequirementId: iqcRequirementId,
      inspectionDate: dateOnly("2026-03-10"),
      inspectorId: qualityUser.id,
      inspectorName: qualityUser.name,
      result: "passed",
      remark: remark("辅料外观抽检通过"),
      attachments: JSON.stringify([{ fileName: "3Q-IQC-002.pdf", filePath: "/ERP/质量部/IQC/3Q-IQC-002.pdf", mimeType: "application/pdf" }]),
      signatures: JSON.stringify([
        buildSignature(303, "inspector", qualityUser.name, "质量部", "2026-03-10T09:20:00", "检验", "本人确认已按照检验规程对来料进行检验，检验结果真实、准确、完整。"),
      ]),
      createdBy: qualityUser.id,
    });

    await insertRow(conn, "iqc_inspection_items", {
      iqcId: iqc2Id,
      itemName: "外观",
      itemType: "qualitative",
      standard: "包装完整、封边均匀",
      acceptedValues: "合格,不合格",
      actualValue: "合格",
      conclusion: "pass",
      sortOrder: 1,
      remark: remark("辅料外观合格"),
    });

    const iqc3Id = await insertRow(conn, "iqc_inspections", {
      inspectionNo: "3Q-IQC-003",
      reportMode: "online",
      goodsReceiptId: goodsReceipt3Id,
      goodsReceiptNo: "3Q-GR-003",
      goodsReceiptItemId: goodsReceipt3ItemId,
      productId: product2Id,
      productCode: "3Q-PROD-002",
      productName: "3Q验证医用硅胶原料",
      specification: "食品级 Φ4.0*2.5mm",
      supplierId: supplier1Id,
      supplierName: "3Q验证-医材原料供应商",
      supplierCode: "3Q-SUP-001",
      batchNo: "3Q-RM-B20260311-99",
      sterilizationBatchNo: null,
      receivedQty: "20.0000",
      sampleQty: "5.0000",
      qualifiedQty: "0.0000",
      unit: "kg",
      inspectionRequirementId: iqcRequirementId,
      inspectionDate: dateOnly("2026-03-11"),
      inspectorId: qualityUser.id,
      inspectorName: qualityUser.name,
      result: "failed",
      remark: remark("尺寸超差，不合格"),
      attachments: JSON.stringify([{ fileName: "3Q-IQC-003-fail.jpg", filePath: "/ERP/质量部/IQC/3Q-IQC-003-fail.jpg", mimeType: "image/jpeg" }]),
      signatures: JSON.stringify([
        buildSignature(304, "inspector", qualityUser.name, "质量部", "2026-03-11T14:05:00", "检验", "本人确认已按照检验规程对来料进行检验，检验结果真实、准确、完整。"),
      ]),
      createdBy: qualityUser.id,
    });

    await insertRow(conn, "iqc_inspection_items", {
      iqcId: iqc3Id,
      itemName: "尺寸",
      itemType: "quantitative",
      standard: "外径 4.0±0.1 mm",
      minVal: "3.9000",
      maxVal: "4.1000",
      unit: "mm",
      measuredValue: "4.35",
      sampleValues: JSON.stringify(["4.33", "4.35", "4.36"]),
      actualValue: "4.35",
      conclusion: "fail",
      sortOrder: 1,
      remark: remark("尺寸超差"),
    });

    const inventoryRawId = await insertRow(conn, "inventory", {
      warehouseId: rawWarehouse.id,
      productId: product2Id,
      materialCode: "3Q-PROD-002",
      itemName: "3Q验证医用硅胶原料",
      batchNo: "3Q-RM-B20260309-01",
      lotNo: "3Q-RM-LOT-001",
      sterilizationBatchNo: null,
      quantity: "30.0000",
      unit: "kg",
      location: "A-01-01",
      status: "qualified",
      productionDate: dateOnly("2026-03-01"),
      expiryDate: dateOnly("2029-03-01"),
      udiPi: null,
      safetyStock: "10.0000",
    });

    const inventoryPackId = await insertRow(conn, "inventory", {
      warehouseId: auxWarehouse.id,
      productId: product3Id,
      materialCode: "3Q-PROD-003",
      itemName: "3Q验证纸塑灭菌袋",
      batchNo: "3Q-PM-B20260310-01",
      lotNo: "3Q-PM-LOT-001",
      sterilizationBatchNo: null,
      quantity: "20.0000",
      unit: "个",
      location: "B-02-03",
      status: "qualified",
      productionDate: dateOnly("2026-03-05"),
      expiryDate: dateOnly("2028-03-05"),
      udiPi: null,
      safetyStock: "30.0000",
    });

    const inventoryFinishedId = await insertRow(conn, "inventory", {
      warehouseId: finishedWarehouse.id,
      productId: product1Id,
      materialCode: "3Q-PROD-001",
      itemName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      lotNo: "3Q-FG-LOT-001",
      sterilizationBatchNo: "3Q-ST-BATCH-001",
      quantity: "15.0000",
      unit: "套",
      location: "FG-01-01",
      status: "qualified",
      productionDate: dateOnly("2026-03-14"),
      expiryDate: dateOnly("2028-03-14"),
      udiPi: "202603143QFG001",
      safetyStock: "20.0000",
    });

    const inventoryDirectId = await insertRow(conn, "inventory", {
      warehouseId: finishedWarehouse.id,
      productId: product4Id,
      materialCode: "3Q-PROD-004",
      itemName: "3Q验证引流固定贴",
      batchNo: "3Q-DS-B20260315-01",
      lotNo: "3Q-DS-LOT-001",
      sterilizationBatchNo: null,
      quantity: "0.0000",
      unit: "盒",
      location: "FG-02-02",
      status: "qualified",
      productionDate: dateOnly("2026-03-08"),
      expiryDate: dateOnly("2027-09-08"),
      udiPi: null,
      safetyStock: "10.0000",
    });

    await insertRow(conn, "inventory_transactions", {
      inventoryId: inventoryRawId,
      warehouseId: rawWarehouse.id,
      type: "purchase_in",
      documentNo: "3Q-IN-001",
      itemName: "3Q验证医用硅胶原料",
      batchNo: "3Q-RM-B20260309-01",
      quantity: "50.0000",
      unit: "kg",
      beforeQty: "0.0000",
      afterQty: "50.0000",
      relatedOrderId: purchaseOrder1Id,
      remark: remark("采购入库，来源 3Q-GR-001"),
      operatorId: purchaseUser.id,
      productId: product2Id,
      sterilizationBatchNo: null,
      shippingFee: null,
      logisticsSupplierId: null,
      logisticsSupplierName: null,
      createdAt: dateTime("2026-03-09T15:20:00"),
    });

    await insertRow(conn, "inventory_transactions", {
      inventoryId: inventoryPackId,
      warehouseId: auxWarehouse.id,
      type: "purchase_in",
      documentNo: "3Q-IN-002",
      itemName: "3Q验证纸塑灭菌袋",
      batchNo: "3Q-PM-B20260310-01",
      quantity: "120.0000",
      unit: "个",
      beforeQty: "0.0000",
      afterQty: "120.0000",
      relatedOrderId: purchaseOrder2Id,
      remark: remark("采购入库，来源 3Q-GR-002"),
      operatorId: purchaseUser.id,
      productId: product3Id,
      sterilizationBatchNo: null,
      shippingFee: null,
      logisticsSupplierId: null,
      logisticsSupplierName: null,
      createdAt: dateTime("2026-03-10T11:30:00"),
    });

    const salesQuote1Id = await insertRow(conn, "sales_quotes", {
      quoteNo: "3Q-SQ-001",
      customerId: customer1Id,
      quoteDate: dateOnly("2026-03-01"),
      validUntil: dateOnly("2026-03-15"),
      deliveryDate: dateOnly("2026-03-20"),
      totalAmount: "10240.00",
      currency: "CNY",
      paymentMethod: "账期支付",
      totalAmountBase: "10240.00",
      exchangeRate: "1.000000",
      status: "converted",
      shippingAddress: "江苏省苏州市工业园区3Q验证大道88号",
      shippingContact: "刘珊",
      shippingPhone: "13800030001",
      tradeTerm: "DDP",
      receiptAccountId: bankAccount.id,
      linkedOrderId: null,
      remark: remark("正式报价，已转订单"),
      salesPersonId: salesUser.id,
      createdBy: salesUser.id,
    });

    await insertRow(conn, "sales_quote_items", {
      quoteId: salesQuote1Id,
      productId: product1Id,
      quantity: "80.0000",
      unit: "套",
      unitPrice: "128.0000",
      amount: "10240.00",
      remark: remark("标准账期价格"),
    });

    const salesQuote2Id = await insertRow(conn, "sales_quotes", {
      quoteNo: "3Q-SQ-002",
      customerId: customer2Id,
      quoteDate: dateOnly("2026-03-06"),
      validUntil: dateOnly("2026-03-12"),
      deliveryDate: dateOnly("2026-03-18"),
      totalAmount: "2880.00",
      currency: "CNY",
      paymentMethod: "预付款",
      totalAmountBase: "2880.00",
      exchangeRate: "1.000000",
      status: "converted",
      shippingAddress: "上海市浦东新区3Q验证支路18号",
      shippingContact: "赵颖",
      shippingPhone: "13800030002",
      tradeTerm: "EXW",
      receiptAccountId: bankAccount.id,
      linkedOrderId: null,
      remark: remark("预付款报价已转订单，后续因未付款关闭"),
      salesPersonId: salesUser.id,
      createdBy: salesUser.id,
    });

    await insertRow(conn, "sales_quote_items", {
      quoteId: salesQuote2Id,
      productId: product4Id,
      quantity: "30.0000",
      unit: "盒",
      unitPrice: "96.0000",
      amount: "2880.00",
      remark: remark("预付款价格"),
    });

    const salesOrder1Id = await insertRow(conn, "sales_orders", {
      orderNo: "3Q-SO-001",
      customerId: customer1Id,
      orderDate: dateOnly("2026-03-02"),
      deliveryDate: dateOnly("2026-03-15"),
      totalAmount: "10240.00",
      currency: "CNY",
      status: "completed",
      paymentStatus: "paid",
      shippingAddress: "江苏省苏州市工业园区3Q验证大道88号",
      isExport: 0,
      remark: remark("账期订单，已完成生产、发货和回款"),
      salesPersonId: salesUser.id,
      createdBy: salesUser.id,
      paymentMethod: "账期支付",
      shippingContact: "刘珊",
      shippingPhone: "13800030001",
      customsStatus: "not_required",
      paymentTermId: null,
      paymentTermType: "account_period",
      prepaymentRatio: null,
      amountBase: "10240.00",
      exchangeRate: "1.000000",
      paidAmount: "10240.00",
      paidAmountBase: "10240.00",
      totalAmountBase: "10240.00",
      depositRate: null,
      depositAmount: null,
      depositPaid: "0.00",
      needsShipping: 1,
      shippingFee: "120.00",
      tradeTerm: "DDP",
      receiptAccountId: bankAccount.id,
    });

    await execute(conn, "UPDATE sales_quotes SET linkedOrderId = ? WHERE id = ?", [salesOrder1Id, salesQuote1Id]);

    await insertRow(conn, "sales_order_items", {
      orderId: salesOrder1Id,
      productId: product1Id,
      quantity: "80.0000",
      unit: "套",
      unitPrice: "128.0000",
      amount: "10240.00",
      deliveredQty: "80.0000",
      remark: remark("已完成发货"),
    });

    const salesOrder2Id = await insertRow(conn, "sales_orders", {
      orderNo: "3Q-SO-002",
      customerId: customer2Id,
      orderDate: dateOnly("2026-03-06"),
      deliveryDate: dateOnly("2026-03-18"),
      totalAmount: "2880.00",
      currency: "CNY",
      status: "cancelled",
      paymentStatus: "unpaid",
      shippingAddress: "上海市浦东新区3Q验证支路18号",
      isExport: 0,
      remark: `[PREPAY_RATIO]50\n${remark("预付款订单未收到预付款，订单关闭")}`,
      salesPersonId: salesUser.id,
      createdBy: salesUser.id,
      paymentMethod: "预付款",
      shippingContact: "赵颖",
      shippingPhone: "13800030002",
      customsStatus: "not_required",
      paymentTermId: null,
      paymentTermType: "prepayment",
      prepaymentRatio: "50.00",
      amountBase: "2880.00",
      exchangeRate: "1.000000",
      paidAmount: "0.00",
      paidAmountBase: "0.00",
      totalAmountBase: "2880.00",
      depositRate: "50.00",
      depositAmount: "1440.00",
      depositPaid: "0.00",
      needsShipping: 1,
      shippingFee: "60.00",
      tradeTerm: "EXW",
      receiptAccountId: bankAccount.id,
    });

    await execute(conn, "UPDATE sales_quotes SET linkedOrderId = ? WHERE id = ?", [salesOrder2Id, salesQuote2Id]);

    await insertRow(conn, "sales_order_items", {
      orderId: salesOrder2Id,
      productId: product4Id,
      quantity: "30.0000",
      unit: "盒",
      unitPrice: "96.0000",
      amount: "2880.00",
      deliveredQty: "0.0000",
      remark: remark("待客户预付款"),
    });

    const productionPlanId = await insertRow(conn, "production_plans", {
      planNo: "3Q-PLAN-001",
      planType: "sales_driven",
      salesOrderId: salesOrder1Id,
      salesOrderNo: "3Q-SO-001",
      salesOrderItemId: null,
      productId: product1Id,
      productName: "3Q验证一次性无菌导尿包",
      orderQty: "80.0000",
      stockQty: "0.0000",
      plannedQty: "100.0000",
      unit: "套",
      plannedStartDate: dateOnly("2026-03-12"),
      plannedEndDate: dateOnly("2026-03-14"),
      priority: "high",
      status: "completed",
      remark: remark("按销售订单驱动生产，含 20 套安全库存"),
      createdBy: productionUser.id,
      batchNo: "3Q-FG-B20260315-01",
      productionOrderId: null,
      supplierId: supplier3Id,
      supplierName: "3Q验证-委外灭菌服务商",
    });

    const productionOrderId = await insertRow(conn, "production_orders", {
      orderNo: "3Q-MO-001",
      productId: product1Id,
      plannedQty: "100.0000",
      completedQty: "100.0000",
      unit: "套",
      batchNo: "3Q-FG-B20260315-01",
      orderType: "finished",
      plannedStartDate: dateOnly("2026-03-12"),
      plannedEndDate: dateOnly("2026-03-14"),
      productionDate: dateOnly("2026-03-14"),
      expiryDate: dateOnly("2028-03-14"),
      actualStartDate: dateOnly("2026-03-12"),
      actualEndDate: dateOnly("2026-03-14"),
      status: "completed",
      salesOrderId: salesOrder1Id,
      planId: productionPlanId,
      remark: remark("完成委外灭菌与放行"),
      createdBy: productionUser.id,
    });

    await execute(conn, "UPDATE production_plans SET productionOrderId = ? WHERE id = ?", [productionOrderId, productionPlanId]);

    const requisitionRemark = JSON.stringify({
      selfServiceMode: false,
      note: remark("按 BOM 自动建议领料"),
      signatures: [
        {
          id: "create-3Q-MR-001",
          action: "create",
          signerName: productionUser.name,
          signedAt: "2026-03-12T08:30:00",
        },
        {
          id: "approve-3Q-MR-001",
          action: "approve",
          signerName: admin.name,
          signedAt: "2026-03-12T08:45:00",
        },
      ],
    });

    const materialRequisitionId = await insertRow(conn, "material_requisition_orders", {
      requisitionNo: "3Q-MR-001",
      productionOrderId,
      productionOrderNo: "3Q-MO-001",
      productionPlanId,
      warehouseId: rawWarehouse.id,
      requisitionDate: dateOnly("2026-03-12"),
      requiredDate: dateOnly("2026-03-12"),
      applicantId: productionUser.id,
      status: "issued",
      items: JSON.stringify([
        {
          materialCode: "3Q-PROD-002",
          materialName: "3Q验证医用硅胶原料",
          specification: "食品级 Φ4.0*2.5mm",
          requiredQty: 20,
          unit: "kg",
          actualQty: 20,
          inventoryId: inventoryRawId,
          warehouseId: rawWarehouse.id,
          warehouseName: rawWarehouse.name,
          batchNo: "3Q-RM-B20260309-01",
          availableQty: 50,
          remark: remark("主原料领料"),
        },
        {
          materialCode: "3Q-PROD-003",
          materialName: "3Q验证纸塑灭菌袋",
          specification: "200mm*300mm",
          requiredQty: 100,
          unit: "个",
          actualQty: 100,
          inventoryId: inventoryPackId,
          warehouseId: auxWarehouse.id,
          warehouseName: auxWarehouse.name,
          batchNo: "3Q-PM-B20260310-01",
          availableQty: 120,
          remark: remark("包装辅料领料"),
        },
      ]),
      remark: requisitionRemark,
      createdBy: productionUser.id,
    });

    await insertRow(conn, "inventory_transactions", {
      inventoryId: inventoryRawId,
      warehouseId: rawWarehouse.id,
      type: "production_out",
      documentNo: "3Q-OUT-001",
      itemName: "3Q验证医用硅胶原料",
      batchNo: "3Q-RM-B20260309-01",
      quantity: "20.0000",
      unit: "kg",
      beforeQty: "50.0000",
      afterQty: "30.0000",
      relatedOrderId: productionOrderId,
      remark: remark("生产领料，来源 3Q-MR-001"),
      operatorId: productionUser.id,
      productId: product2Id,
      sterilizationBatchNo: null,
      shippingFee: null,
      logisticsSupplierId: null,
      logisticsSupplierName: null,
      createdAt: dateTime("2026-03-12T09:00:00"),
    });

    await insertRow(conn, "inventory_transactions", {
      inventoryId: inventoryPackId,
      warehouseId: auxWarehouse.id,
      type: "production_out",
      documentNo: "3Q-OUT-002",
      itemName: "3Q验证纸塑灭菌袋",
      batchNo: "3Q-PM-B20260310-01",
      quantity: "100.0000",
      unit: "个",
      beforeQty: "120.0000",
      afterQty: "20.0000",
      relatedOrderId: productionOrderId,
      remark: remark("生产领料，来源 3Q-MR-001"),
      operatorId: productionUser.id,
      productId: product3Id,
      sterilizationBatchNo: null,
      shippingFee: null,
      logisticsSupplierId: null,
      logisticsSupplierName: null,
      createdAt: dateTime("2026-03-12T09:05:00"),
    });

    await insertRow(conn, "production_records", {
      recordNo: "3Q-PRD-001",
      productionOrderId,
      recordType: "first_piece",
      productionOrderNo: "3Q-MO-001",
      productId: product1Id,
      productName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      plannedQty: "100.0000",
      actualQty: "5.0000",
      defectQty: "0.0000",
      unit: "套",
      operatorId: productionUser.id,
      operatorName: productionUser.name,
      productionDate: dateOnly("2026-03-13"),
      shift: "morning",
      status: "completed",
      qualityNotes: remark("首件确认通过"),
      remark: remark("首件记录"),
      createdBy: productionUser.id,
      firstPieceBasis: "工艺卡 3Q-GY-01",
      firstPieceBasisVersion: "V1.0",
      specification: "A型 16Fr",
      processType: "装配",
      processName: "组装与封装",
      workshopName: "净化车间",
      productionTeam: "A班",
      operator: productionUser.name,
      inspector: qualityUser.name,
      cleanlinessLevel: "10万级",
      pressureDiff: "12.50",
      storageArea: "首件暂存区",
      issuedQty: "5.0000",
      qualifiedQty: "5.0000",
      detailItems: JSON.stringify([
        { itemName: "外观", standard: "无毛刺", result: "合格" },
        { itemName: "连接强度", standard: "≥15N", result: "18N" },
      ]),
      equipmentItems: JSON.stringify([{ name: "热封机", code: "EQ-3Q-01", status: "正常" }]),
      moldItems: JSON.stringify([{ name: "装配工装", code: "MJ-3Q-01", status: "正常" }]),
      documentVersion: "V1.0",
      workstationName: "装配工位 1",
      workstationId: 101,
      recordDate: dateOnly("2026-03-13"),
      scrapQty: "0",
      temperatureLimit: "18-26",
      humidityLimit: "45-65",
      firstPieceResult: "qualified",
      firstPieceInspector: qualityUser.name,
      recordTime: "08:30",
      materialItems: JSON.stringify([
        { code: "3Q-PROD-002", name: "3Q验证医用硅胶原料", batchNo: "3Q-RM-B20260309-01", qty: "1.0000", unit: "kg" },
      ]),
    });

    await insertRow(conn, "production_records", {
      recordNo: "3Q-PRD-002",
      productionOrderId,
      recordType: "material_usage",
      materialCode: "3Q-PROD-002",
      materialName: "3Q验证医用硅胶原料",
      materialUsedQty: "20.000",
      materialUnit: "kg",
      productionOrderNo: "3Q-MO-001",
      productId: product1Id,
      productName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      plannedQty: "100.0000",
      actualQty: "100.0000",
      defectQty: "2.0000",
      unit: "套",
      operatorId: productionUser.id,
      operatorName: productionUser.name,
      productionDate: dateOnly("2026-03-13"),
      shift: "afternoon",
      status: "completed",
      qualityNotes: remark("制程稳定"),
      remark: remark("主原料耗用记录"),
      createdBy: productionUser.id,
      specification: "A型 16Fr",
      processType: "投料",
      processName: "主原料投料",
      workshopName: "净化车间",
      productionTeam: "A班",
      operator: productionUser.name,
      inspector: qualityUser.name,
      cleanlinessLevel: "10万级",
      pressureDiff: "11.80",
      storageArea: "原料暂存区",
      issuedQty: "20.0000",
      qualifiedQty: "98.0000",
      detailItems: JSON.stringify([{ itemName: "原料批次核对", standard: "批次一致", result: "一致" }]),
      equipmentItems: JSON.stringify([{ name: "投料称", code: "EQ-3Q-02", status: "已校准" }]),
      moldItems: JSON.stringify([]),
      documentVersion: "V1.0",
      workstationName: "投料工位",
      workstationId: 102,
      recordDate: dateOnly("2026-03-13"),
      scrapQty: "2",
      materialSpec: "食品级 Φ4.0*2.5mm",
      materialBatchNo: "3Q-RM-B20260309-01",
      usedQty: "20.0000",
      usedUnit: "kg",
      recordTime: "13:40",
      materialItems: JSON.stringify([
        { code: "3Q-PROD-002", name: "3Q验证医用硅胶原料", batchNo: "3Q-RM-B20260309-01", qty: "20.0000", unit: "kg" },
        { code: "3Q-PROD-003", name: "3Q验证纸塑灭菌袋", batchNo: "3Q-PM-B20260310-01", qty: "100.0000", unit: "个" },
      ]),
    });

    const ipqcRemark = JSON.stringify({
      productCode: "3Q-PROD-001",
      process: "组装与封装",
      inspectionType: "patrol",
      result: "qualified",
      inspector: qualityUser.name,
      workstation: "装配工位 1",
      remarks: remark("巡检结果正常，尺寸和流量均符合要求"),
      inspectionItems: [
        { name: "装配完整性", standard: "组件装配完整，无错漏装", result: "合格", conclusion: "qualified" },
        { name: "流量测试", standard: "20-24 ml/min", result: "22 ml/min", conclusion: "qualified" },
      ],
      signatures: [
        buildSignature(401, "inspector", qualityUser.name, "质量部", "2026-03-13T14:30:00", "巡检", "本人确认已按照过程检验规程进行检验，检验结果真实、准确、完整。"),
        buildSignature(402, "approver", admin.name, "管理部", "2026-03-13T15:00:00", "批准", "本人批准该过程检验报告，同意检验结论。"),
      ],
      sourceType: "quality",
    });

    const ipqcId = await insertRow(conn, "quality_inspections", {
      inspectionNo: "3Q-IPQC-001",
      type: "IPQC",
      relatedDocNo: "3Q-MO-001",
      itemName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      sampleQty: "10.0000",
      inspectedQty: "10.0000",
      qualifiedQty: "10.0000",
      unqualifiedQty: "0.0000",
      result: "qualified",
      inspectorId: qualityUser.id,
      inspectionDate: dateOnly("2026-03-13"),
      remark: ipqcRemark,
      productionOrderId,
      productionOrderNo: "3Q-MO-001",
    });

    const routingCardId = await insertRow(conn, "production_routing_cards", {
      cardNo: "3Q-RC-001",
      productionOrderId,
      productionOrderNo: "3Q-MO-001",
      productId: product1Id,
      productName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      quantity: "100.0000",
      unit: "套",
      currentProcess: "委外灭菌",
      nextProcess: "成品检验",
      needsSterilization: 1,
      status: "completed",
      remark: remark("完成委外灭菌回厂"),
      createdBy: productionUser.id,
    });

    const sterilizationOrderId = await insertRow(conn, "sterilization_orders", {
      orderNo: "3Q-ST-001",
      routingCardId,
      routingCardNo: "3Q-RC-001",
      productionOrderId,
      productionOrderNo: "3Q-MO-001",
      productId: product1Id,
      productName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      quantity: "100.0000",
      unit: "套",
      sterilizationMethod: "EO",
      supplierId: supplier3Id,
      supplierName: "3Q验证-委外灭菌服务商",
      sendDate: dateOnly("2026-03-13"),
      expectedReturnDate: dateOnly("2026-03-14"),
      actualReturnDate: dateOnly("2026-03-14"),
      status: "qualified",
      remark: remark("委外灭菌完成并回厂"),
      createdBy: productionUser.id,
      sterilizationBatchNo: "3Q-ST-BATCH-001",
      arrivedAt: dateTime("2026-03-14T09:15:00"),
      arrivedBy: productionUser.id,
    });

    const productionWarehouseEntryRemark = JSON.stringify({
      note: remark("OQC 放行后完成成品入库"),
      sterilizationProof: proofMeta,
    });

    const productionWarehouseEntryId = await insertRow(conn, "production_warehouse_entries", {
      entryNo: "3Q-WE-001",
      productionOrderId,
      productionOrderNo: "3Q-MO-001",
      sterilizationOrderId,
      sterilizationOrderNo: "3Q-ST-001",
      productId: product1Id,
      productName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      quantity: "95.0000",
      sterilizedQty: 100,
      inspectionRejectQty: 2,
      sampleQty: 2,
      modifyReason: remark("系统保留 1 套做稳定性观察"),
      modifiedBy: qualityUser.id,
      unit: "套",
      targetWarehouseId: finishedWarehouse.id,
      applicantId: productionUser.id,
      applicationDate: dateOnly("2026-03-14"),
      status: "completed",
      remark: productionWarehouseEntryRemark,
      createdBy: productionUser.id,
      quantityModifyReason: remark("系统保留 1 套做稳定性观察"),
      sterilizationBatchNo: "3Q-ST-BATCH-001",
    });

    const oqcRemark = JSON.stringify({
      productCode: "3Q-PROD-001",
      sterilizationBatchNo: "3Q-ST-BATCH-001",
      quantity: "100",
      unit: "套",
      samplingQty: 8,
      rejectQty: 2,
      sampleRetainQty: 2,
      result: "qualified",
      inspector: qualityUser.name,
      remarks: remark("放行检验完成，允许入库 95 套"),
      warehouseEntryId: productionWarehouseEntryId,
      warehouseEntryNo: "3Q-WE-001",
      inspectionItems: [
        {
          name: "无菌屏障完整性",
          standard: "包装完整，封边无破损",
          sampleQty: 4,
          result: "抽检 4 套合格",
          conclusion: "qualified",
          children: [],
          records: [
            {
              id: "3Q-OQC-001-R1",
              sampleQty: 4,
              result: "4/4 合格",
              conclusion: "qualified",
              inspector: qualityUser.name,
              inspectionTime: "2026-03-14T10:10",
              remark: remark("包装完整"),
              details: [
                {
                  name: "封边检查",
                  standard: "无破口",
                  sampleQty: 4,
                  sampleValues: ["合格", "合格", "合格", "合格"],
                  result: "全部合格",
                  conclusion: "qualified",
                  remark: remark("封边稳定"),
                  attachments: [],
                },
              ],
            },
          ],
        },
        {
          name: "标签信息",
          standard: "批号、UDI、有效期打印正确",
          sampleQty: 4,
          result: "1 套标签偏移，复贴后留样",
          conclusion: "qualified",
          children: [],
          records: [
            {
              id: "3Q-OQC-001-R2",
              sampleQty: 4,
              result: "3 合格 / 1 调整后留样",
              conclusion: "qualified",
              inspector: qualityUser.name,
              inspectionTime: "2026-03-14T10:25",
              remark: remark("标签复核完成"),
              details: [
                {
                  name: "批号核对",
                  standard: "与生产批号一致",
                  sampleQty: 4,
                  sampleValues: ["一致", "一致", "一致", "一致"],
                  result: "一致",
                  conclusion: "qualified",
                  remark: remark("信息一致"),
                  attachments: [],
                },
              ],
            },
          ],
        },
      ],
      signatures: [
        buildSignature(501, "inspector", qualityUser.name, "质量部", "2026-03-14T10:35:00", "检验", "本人确认已按照成品检验规程进行检验，检验结果真实、准确、完整。"),
        buildSignature(502, "reviewer", admin.name, "管理部", "2026-03-14T10:45:00", "复核", "本人确认已复核成品检验记录，数据真实可靠，检验方法符合规定。"),
        buildSignature(503, "approver", admin.name, "管理部", "2026-03-14T11:00:00", "批准放行", "本人批准该成品检验报告，产品符合放行条件。"),
      ],
      releaseForm: {
        releaseQty: "95",
        reviewItems: [
          { itemName: "包装完整性", reviewStandard: "无破损", decision: "qualified" },
          { itemName: "标签一致性", reviewStandard: "批号/UDI/有效期一致", decision: "qualified" },
        ],
        decision: "approve",
        remark: remark("同意放行入库"),
      },
    });

    const oqcId = await insertRow(conn, "quality_inspections", {
      inspectionNo: "3Q-OQC-001",
      type: "OQC",
      relatedDocNo: "3Q-PROD-001",
      itemName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      sampleQty: "2.0000",
      inspectedQty: "100.0000",
      qualifiedQty: "95.0000",
      unqualifiedQty: "2.0000",
      result: "qualified",
      inspectorId: qualityUser.id,
      inspectionDate: dateOnly("2026-03-14"),
      remark: oqcRemark,
      productionOrderId,
      productionOrderNo: "3Q-MO-001",
      sterilizationOrderId,
      sterilizationOrderNo: "3Q-ST-001",
      rejectQty: 2,
      sampleRetainQty: 2,
    });

    await insertRow(conn, "inventory_transactions", {
      inventoryId: inventoryFinishedId,
      warehouseId: finishedWarehouse.id,
      type: "production_in",
      documentNo: "3Q-WE-001",
      itemName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      quantity: "95.0000",
      unit: "套",
      beforeQty: "0.0000",
      afterQty: "95.0000",
      relatedOrderId: productionOrderId,
      remark: remark("生产入库，来源 3Q-WE-001 / 3Q-OQC-001"),
      operatorId: productionUser.id,
      productId: product1Id,
      sterilizationBatchNo: "3Q-ST-BATCH-001",
      shippingFee: null,
      logisticsSupplierId: null,
      logisticsSupplierName: null,
      createdAt: dateTime("2026-03-14T11:30:00"),
    });

    await insertRow(conn, "inventory_transactions", {
      inventoryId: inventoryFinishedId,
      warehouseId: finishedWarehouse.id,
      type: "sales_out",
      documentNo: "3Q-SHIP-001",
      itemName: "3Q验证一次性无菌导尿包",
      batchNo: "3Q-FG-B20260315-01",
      quantity: "80.0000",
      unit: "套",
      beforeQty: "95.0000",
      afterQty: "15.0000",
      relatedOrderId: salesOrder1Id,
      remark: remark("销售出库，已完成发货"),
      operatorId: salesUser.id,
      productId: product1Id,
      sterilizationBatchNo: "3Q-ST-BATCH-001",
      shippingFee: "120.00",
      logisticsSupplierId: supplier4Id,
      logisticsSupplierName: "3Q验证-物流服务商",
      createdAt: dateTime("2026-03-15T09:20:00"),
    });

    const accountsReceivableId = await insertRow(conn, "accounts_receivable", {
      invoiceNo: "AR-3Q-SO-001",
      customerId: customer1Id,
      salesOrderId: salesOrder1Id,
      amount: "10240.00",
      paidAmount: "10240.00",
      currency: "CNY",
      invoiceDate: dateOnly("2026-03-15"),
      dueDate: dateOnly("2026-04-14"),
      status: "paid",
      remark: remark("账期订单已完成回款"),
      amountBase: "10240.00",
      exchangeRate: "1.000000",
      bankAccountId: bankAccount.id,
      paymentMethod: "账期支付",
      receiptDate: dateOnly("2026-03-20"),
      createdBy: financeUser.id,
    });

    const accountsPayable1Id = await insertRow(conn, "accounts_payable", {
      invoiceNo: "3Q-AP-001",
      supplierId: supplier1Id,
      purchaseOrderId: purchaseOrder1Id,
      amount: "9000.00",
      paidAmount: "9000.00",
      currency: "CNY",
      invoiceDate: dateOnly("2026-03-10"),
      dueDate: dateOnly("2026-04-09"),
      status: "paid",
      remark: remark("原料款已支付"),
      amountBase: "9000.00",
      exchangeRate: "1.000000",
      bankAccountId: bankAccount.id,
      supplierName: "3Q验证-医材原料供应商",
      paymentMethod: "账期支付",
      paymentDate: dateOnly("2026-03-15"),
      createdBy: financeUser.id,
    });

    const accountsPayable2Id = await insertRow(conn, "accounts_payable", {
      invoiceNo: "3Q-AP-002",
      supplierId: supplier2Id,
      purchaseOrderId: purchaseOrder2Id,
      amount: "216.00",
      paidAmount: "216.00",
      currency: "CNY",
      invoiceDate: dateOnly("2026-03-10"),
      dueDate: dateOnly("2026-03-25"),
      status: "paid",
      remark: remark("包装辅料已完成付款"),
      amountBase: "216.00",
      exchangeRate: "1.000000",
      bankAccountId: bankAccount.id,
      supplierName: "3Q验证-灭菌包装供应商",
      paymentMethod: "预付款",
      paymentDate: dateOnly("2026-03-16"),
      createdBy: financeUser.id,
    });

    await insertRow(conn, "received_invoices", {
      invoiceNo: "3Q-RINV-001",
      invoiceCode: "320026000001",
      invoiceType: "vat_special",
      supplierId: supplier1Id,
      supplierName: "3Q验证-医材原料供应商",
      payableIds: JSON.stringify([accountsPayable1Id]),
      relatedOrderNo: "3Q-PO-001",
      invoiceDate: dateOnly("2026-03-10"),
      receiveDate: dateOnly("2026-03-11"),
      amountExTax: "7964.60",
      taxRate: "13.00",
      taxAmount: "1035.40",
      totalAmount: "9000.00",
      verifyCode: "3QINVRCV001",
      status: "booked",
      remark: remark("已完成收票入账"),
      createdBy: financeUser.id,
    });

    await insertRow(conn, "received_invoices", {
      invoiceNo: "3Q-RINV-002",
      invoiceCode: "320026000002",
      invoiceType: "electronic",
      supplierId: supplier2Id,
      supplierName: "3Q验证-灭菌包装供应商",
      payableIds: JSON.stringify([accountsPayable2Id]),
      relatedOrderNo: "3Q-PO-002",
      invoiceDate: dateOnly("2026-03-10"),
      receiveDate: dateOnly("2026-03-10"),
      amountExTax: "191.15",
      taxRate: "13.00",
      taxAmount: "24.85",
      totalAmount: "216.00",
      verifyCode: "3QINVRCV002",
      status: "booked",
      remark: remark("电子发票已收票入账"),
      createdBy: financeUser.id,
    });

    await insertRow(conn, "issued_invoices", {
      invoiceNo: "3Q-IINV-001",
      invoiceType: "vat_special",
      customerId: customer1Id,
      customerName: "3Q验证-康泽医疗",
      receivableIds: JSON.stringify([accountsReceivableId]),
      relatedOrderNo: "3Q-SO-001",
      reconcileMonth: "2026-03",
      invoiceDate: dateOnly("2026-03-15"),
      amountExTax: "9061.95",
      taxRate: "13.00",
      taxAmount: "1178.05",
      totalAmount: "10240.00",
      bankAccountId: bankAccount.id,
      bankAccount: `${bankAccount.accountName} / ${bankAccount.bankName} / ${bankAccount.accountNo}`,
      status: "issued",
      remark: remark("已给客户开票"),
      createdBy: financeUser.id,
    });

    await insertRow(conn, "payment_records", {
      recordNo: "3Q-PAY-001",
      type: "payment",
      relatedType: "purchase_order",
      relatedId: purchaseOrder1Id,
      relatedNo: "3Q-PO-001",
      customerId: null,
      supplierId: supplier1Id,
      amount: "9000.00",
      currency: "CNY",
      amountBase: "9000.00",
      exchangeRate: "1.000000",
      bankAccountId: bankAccount.id,
      paymentDate: dateOnly("2026-03-15"),
      paymentMethod: "银行转账",
      remark: remark("支付原料采购款"),
      operatorId: financeUser.id,
    });

    await insertRow(conn, "payment_records", {
      recordNo: "3Q-PAY-002",
      type: "payment",
      relatedType: "purchase_order",
      relatedId: purchaseOrder2Id,
      relatedNo: "3Q-PO-002",
      customerId: null,
      supplierId: supplier2Id,
      amount: "216.00",
      currency: "CNY",
      amountBase: "216.00",
      exchangeRate: "1.000000",
      bankAccountId: bankAccount.id,
      paymentDate: dateOnly("2026-03-16"),
      paymentMethod: "银行转账",
      remark: remark("支付包装辅料采购款"),
      operatorId: financeUser.id,
    });

    await insertRow(conn, "payment_records", {
      recordNo: "3Q-REC-001",
      type: "receipt",
      relatedType: "sales_order",
      relatedId: salesOrder1Id,
      relatedNo: "3Q-SO-001",
      customerId: customer1Id,
      supplierId: null,
      amount: "6000.00",
      currency: "CNY",
      amountBase: "6000.00",
      exchangeRate: "1.000000",
      bankAccountId: bankAccount.id,
      paymentDate: dateOnly("2026-03-15"),
      paymentMethod: "银行转账",
      remark: remark("客户首笔回款"),
      operatorId: financeUser.id,
    });

    await insertRow(conn, "payment_records", {
      recordNo: "3Q-REC-002",
      type: "receipt",
      relatedType: "sales_order",
      relatedId: salesOrder1Id,
      relatedNo: "3Q-SO-001",
      customerId: customer1Id,
      supplierId: null,
      amount: "4240.00",
      currency: "CNY",
      amountBase: "4240.00",
      exchangeRate: "1.000000",
      bankAccountId: bankAccount.id,
      paymentDate: dateOnly("2026-03-20"),
      paymentMethod: "银行转账",
      remark: remark("客户尾款回收"),
      operatorId: financeUser.id,
    });

    const approvals = [
      { orderId: salesOrder1Id, orderType: "sales", action: "submit", approver: salesUser.name, approverId: salesUser.id, comment: remark("销售订单提交审批") },
      { orderId: salesOrder1Id, orderType: "sales", action: "approve", approver: admin.name, approverId: admin.id, comment: remark("销售订单审批通过") },
      { orderId: salesOrder2Id, orderType: "sales", action: "submit", approver: salesUser.name, approverId: salesUser.id, comment: remark("预付款订单提交") },
      { orderId: purchaseOrder1Id, orderType: "purchase", action: "submit", approver: purchaseUser.name, approverId: purchaseUser.id, comment: remark("采购单提交") },
      { orderId: purchaseOrder1Id, orderType: "purchase", action: "approve", approver: admin.name, approverId: admin.id, comment: remark("采购单审批通过") },
      { orderId: purchaseOrder2Id, orderType: "purchase", action: "approve", approver: admin.name, approverId: admin.id, comment: remark("采购单审批通过") },
      { orderId: productionOrderId, orderType: "production", action: "submit", approver: productionUser.name, approverId: productionUser.id, comment: remark("生产指令提交") },
      { orderId: productionOrderId, orderType: "production", action: "approve", approver: admin.name, approverId: admin.id, comment: remark("生产指令审批通过") },
    ];

    for (const item of approvals) {
      await insertRow(conn, "order_approvals", item);
    }

    const logEntries = [
      {
        module: "customer",
        action: "create",
        targetType: "客户",
        targetId: String(customer1Id),
        targetName: "3Q验证-康泽医疗",
        description: remark("创建客户主数据"),
        operatorId: salesUser.id,
        operatorName: salesUser.name,
        operatorRole: "user",
        operatorDepartment: "销售部",
      },
      {
        module: "supplier",
        action: "create",
        targetType: "供应商",
        targetId: String(supplier1Id),
        targetName: "3Q验证-医材原料供应商",
        description: remark("创建供应商主数据"),
        operatorId: purchaseUser.id,
        operatorName: purchaseUser.name,
        operatorRole: "user",
        operatorDepartment: "采购部",
      },
      {
        module: "order",
        action: "approve",
        targetType: "采购订单",
        targetId: String(purchaseOrder1Id),
        targetName: "3Q-PO-001",
        description: remark("采购订单审批并完成"),
        operatorId: admin.id,
        operatorName: admin.name,
        operatorRole: "admin",
        operatorDepartment: "管理部",
      },
      {
        module: "quality",
        action: "approve",
        targetType: "来料检验",
        targetId: String(iqc1Id),
        targetName: "3Q-IQC-001",
        description: remark("IQC 合格放行"),
        operatorId: qualityUser.id,
        operatorName: qualityUser.name,
        operatorRole: "user",
        operatorDepartment: "质量部",
      },
      {
        module: "production",
        action: "create",
        targetType: "生产指令",
        targetId: String(productionOrderId),
        targetName: "3Q-MO-001",
        description: remark("创建生产指令并执行"),
        operatorId: productionUser.id,
        operatorName: productionUser.name,
        operatorRole: "user",
        operatorDepartment: "生产部",
      },
      {
        module: "inventory",
        action: "create",
        targetType: "库存流水",
        targetId: "3Q-IN-001",
        targetName: "3Q-IN-001",
        description: remark("采购入库完成"),
        operatorId: purchaseUser.id,
        operatorName: purchaseUser.name,
        operatorRole: "user",
        operatorDepartment: "采购部",
      },
      {
        module: "quality",
        action: "approve",
        targetType: "成品检验",
        targetId: String(oqcId),
        targetName: "3Q-OQC-001",
        description: remark("OQC 合格放行"),
        operatorId: qualityUser.id,
        operatorName: qualityUser.name,
        operatorRole: "user",
        operatorDepartment: "质量部",
      },
      {
        module: "inventory",
        action: "create",
        targetType: "出库单",
        targetId: "3Q-SHIP-001",
        targetName: "3Q-SHIP-001",
        description: remark("销售出库完成"),
        operatorId: salesUser.id,
        operatorName: salesUser.name,
        operatorRole: "user",
        operatorDepartment: "销售部",
      },
      {
        module: "finance",
        action: "create",
        targetType: "应收账款",
        targetId: String(accountsReceivableId),
        targetName: "AR-3Q-SO-001",
        description: remark("生成应收并登记回款"),
        operatorId: financeUser.id,
        operatorName: financeUser.name,
        operatorRole: "user",
        operatorDepartment: "财务部",
      },
      {
        module: "order",
        action: "delete",
        targetType: "销售报价单",
        targetId: "3Q-SQ-DEL-001",
        targetName: "3Q-SQ-DEL-001",
        description: remark("删除草稿报价并进入回收箱"),
        operatorId: admin.id,
        operatorName: admin.name,
        operatorRole: "admin",
        operatorDepartment: "管理部",
      },
    ];

    for (const log of logEntries) {
      await insertRow(conn, "operation_logs", {
        ...log,
        result: "success",
        previousData: null,
        newData: JSON.stringify({ tag: TAG, targetName: log.targetName }),
        changedFields: null,
        ipAddress: "127.0.0.1",
        userAgent: "seed-3q-validation.ts",
        deviceType: "PC",
        browser: "Node",
      });
    }

    await insertRow(conn, "recycle_bin", {
      entityType: "销售报价单",
      sourceTable: "sales_quotes",
      sourceId: 930001,
      displayName: "3Q-SQ-DEL-001",
      payload: JSON.stringify({
        tag: TAG,
        quoteNo: "3Q-SQ-DEL-001",
        customerName: "3Q验证-天瑞耗材",
        status: "draft",
        totalAmount: "1680.00",
        deletedReason: "验证删除回收流程",
      }),
      status: "active",
      deletedBy: admin.id,
      deletedAt: dateTime("2026-03-15T12:10:00"),
      expiresAt: dateTime("2026-04-14T12:10:00"),
      restoredAt: null,
      restoredBy: null,
    });

    await conn.commit();

    const counts = await queryRows<{ name: string; count: number }>(
      conn,
      `
      SELECT 'customers' AS name, COUNT(*) AS count FROM customers WHERE code LIKE '3Q-%'
      UNION ALL SELECT 'suppliers', COUNT(*) FROM suppliers WHERE code LIKE '3Q-%'
      UNION ALL SELECT 'products', COUNT(*) FROM products WHERE code LIKE '3Q-%'
      UNION ALL SELECT 'sales_quotes', COUNT(*) FROM sales_quotes WHERE quoteNo LIKE '3Q-%'
      UNION ALL SELECT 'sales_orders', COUNT(*) FROM sales_orders WHERE orderNo LIKE '3Q-%'
      UNION ALL SELECT 'purchase_orders', COUNT(*) FROM purchase_orders WHERE orderNo LIKE '3Q-%'
      UNION ALL SELECT 'goods_receipts', COUNT(*) FROM goods_receipts WHERE receiptNo LIKE '3Q-%'
      UNION ALL SELECT 'iqc_inspections', COUNT(*) FROM iqc_inspections WHERE inspectionNo LIKE '3Q-%'
      UNION ALL SELECT 'quality_inspections', COUNT(*) FROM quality_inspections WHERE inspectionNo LIKE '3Q-%'
      UNION ALL SELECT 'production_orders', COUNT(*) FROM production_orders WHERE orderNo LIKE '3Q-%'
      UNION ALL SELECT 'material_requisition_orders', COUNT(*) FROM material_requisition_orders WHERE requisitionNo LIKE '3Q-%'
      UNION ALL SELECT 'production_warehouse_entries', COUNT(*) FROM production_warehouse_entries WHERE entryNo LIKE '3Q-%'
      UNION ALL SELECT 'inventory_transactions', COUNT(*) FROM inventory_transactions WHERE documentNo LIKE '3Q-%'
      UNION ALL SELECT 'accounts_receivable', COUNT(*) FROM accounts_receivable WHERE invoiceNo LIKE 'AR-3Q-%'
      UNION ALL SELECT 'accounts_payable', COUNT(*) FROM accounts_payable WHERE invoiceNo LIKE '3Q-%'
      UNION ALL SELECT 'payment_records', COUNT(*) FROM payment_records WHERE recordNo LIKE '3Q-%'
      UNION ALL SELECT 'recycle_bin', COUNT(*) FROM recycle_bin WHERE displayName LIKE '3Q-%'
      `,
    );

    console.log("3Q 验证数据已写入数据库");
    console.log("可搜索关键词: 3Q- / 3Q验证 / [3Q-VAL-20260315]");
    console.log("关键单号:");
    console.log("  销售报价: 3Q-SQ-001, 3Q-SQ-002");
    console.log("  销售订单: 3Q-SO-001, 3Q-SO-002");
    console.log("  采购申请: 3Q-PR-001, 3Q-PR-002");
    console.log("  采购订单: 3Q-PO-001, 3Q-PO-002, 3Q-PO-003");
    console.log("  到货单: 3Q-GR-001, 3Q-GR-002, 3Q-GR-003");
    console.log("  IQC: 3Q-IQC-001, 3Q-IQC-002, 3Q-IQC-003");
    console.log("  生产计划/指令: 3Q-PLAN-001, 3Q-MO-001");
    console.log("  领料/委外/入库: 3Q-MR-001, 3Q-ST-001, 3Q-WE-001");
    console.log("  IPQC/OQC: 3Q-IPQC-001, 3Q-OQC-001");
    console.log("  库存流水: 3Q-IN-001, 3Q-IN-002, 3Q-OUT-001, 3Q-OUT-002, 3Q-SHIP-001");
    console.log("  财务: AR-3Q-SO-001, 3Q-AP-001, 3Q-AP-002, 3Q-RINV-001, 3Q-RINV-002, 3Q-IINV-001, 3Q-PAY-001, 3Q-PAY-002, 3Q-REC-001, 3Q-REC-002");
    console.log("  删除验证: 3Q-SQ-DEL-001");
    console.log("");
    for (const row of counts) {
      console.log(`${row.name}: ${row.count}`);
    }
  } catch (error) {
    await conn.rollback();
    throw error;
  } finally {
    await conn.end();
  }
}

main().catch((error) => {
  console.error("3Q 验证数据生成失败");
  console.error(error);
  process.exit(1);
});
